# -------------------------------------------------------------------
# Base Model Configuration
# -------------------------------------------------------------------
model_name: "../GLiNER/simcse"
labels_encoder: null
name: "span level gliner"
max_width: 12
hidden_size: 768
dropout: 0.3
fine_tune: true
subtoken_pooling: first
fuse_layers: false
post_fusion_schema: "l2l-l2t-t2t"
span_mode: markerV0

# -------------------------------------------------------------------
# Training Parameters
# -------------------------------------------------------------------
num_steps: 100000
train_batch_size: 8
gradient_accumulation_steps: 4
eval_every: 2000
warmup_ratio: 0.05
scheduler_type: "cosine"
dataloader_drop_last: true

# -------------------------------------------------------------------
# Loss Function
# -------------------------------------------------------------------
loss_alpha: 0.75
loss_gamma: 0
label_smoothing: 0
loss_reduction: "sum"

# -------------------------------------------------------------------
# Learning Rate and Optimization
# -------------------------------------------------------------------
lr_encoder: 0.0
lr_others: 3e-5
weight_decay_encoder: 0.01
weight_decay_other: 0.01
max_grad_norm: 10.0

# -------------------------------------------------------------------
# Data and Directory Paths
# -------------------------------------------------------------------
log_dir: gliner_simcse_frozen
train_data: "../GLiNER/pilener_train.json"
train_data_dir: "../GLiNER/data/train"
val_data_dir: "../GLiNER/data/eval"

# Pretrained Model Path
prev_path: null
save_total_limit: 3

# -------------------------------------------------------------------
# Advanced Training Settings
# -------------------------------------------------------------------
size_sup: -1
max_types: 30
shuffle_types: true
random_drop: true
max_neg_type_ratio: 1
max_len: 256
freeze_token_rep: false

# Data filtering
min_entity_examples: 10

# -------------------------------------------------------------------
# Evaluation and Early Stopping Configuration
# -------------------------------------------------------------------
early_stopping_patience: 50
use_threshold_scheduler: true
threshold_initial: 0.01
threshold_final: 0.5
threshold_warmup_steps: 5000
threshold_schedule_type: "linear"
fixed_evaluation_threshold: 0.5